### ISSUE TITLE
Realtime

### ISSUE THREAD

**Issue by peixinx** [bearpaw/PyraNet#1]
How is the realtime perfommance? It's said that  this model needs 45.9GFLOPs per image. Does it works on videos?

**Comment by bearpaw** [comment]
Hi @peixinx . Our model is not real time. The test time of our final model (downloadable from [Google Drive](https://drive.google.com/open?id=0B63t5HSgY4SQbmJoRV9fOTBFTlU)) is about 280 ms per image on a single Titan Black (6GB) GPU.
