### ISSUE TITLE
Evaluation on LSP Dataset

### ISSUE THREAD

**Issue by MissYOLY** [bearpaw/PyraNet#11]
Hi,@bearpaw
Thank you for sharing your wonderful work!
Based on the steps you provided, after training on the LSP data set, generate a .h5 prediction file, but in this evaluation code: http://human-pose.mpi-inf.mpg.de/results/lsp/evalLSP. Zip, it needs to use .mat files to make predictions. So what I want to ask is how to generate such a .mat file ? Have you implemented such functions in your codes?

**Comment by 738654805** [comment]
@MissYOLY how to train on LSP dataset.In this work,Options only include mpii and mpii-lsp.

**Comment by MissYOLY** [comment]
@738654805 I just set mpii-lsp for train LSP.

**Comment by 738654805** [comment]
@MissYOLY thanks for your reply.You mean the option mpii-lsp is equal to load lsp dataset?not mpii+lsp.

**Comment by MissYOLY** [comment]
The option mpii-lsp is equivalent to loading the lsp+mpii data set. Many methods are combined training with mpii and lsp, and then tested with the lsp test set.

**Comment by MissYOLY** [comment]
@738654805

**Comment by 738654805** [comment]
got it.thanks.
BTW,do you have access to download the MPII+LSP data set.

**Comment by MissYOLY** [comment]
Yes, just change the option.

**Comment by bearpaw** [comment]
@MissYOLY Matlab can read h5 files. You can also use python to convert h5 to mat files. Just google it :)
