### ISSUE TITLE
Do you  just use 'LEEDS_annotations.json' to train a model for LSP?

### ISSUE THREAD

**Issue by Binyr** [bearpaw/PyraNet#17]
Sorry for multiple open issue. I just hesitate how to express my doubts and I am newcomer to github.
I am not skilled at pytorch. Therefore, I am not sure if your code uses 'LEEDS_annotations.json' directly to train a model on LSP dataset.
Thank you very much!

**Comment by bearpaw** [comment]
There is no "correct" way. You can either train with LSP only or LSP + MPII. It depends on your task, and which method you want to compare your method with. 

I report my result here (Yang et al., ICCV'17*): http://human-pose.mpi-inf.mpg.de/#related_benchmarks
`*` indicates methods trained when adding MPII training set to the LSP training and LSP extended training set.

**Comment by Binyr** [comment]
Thank you for your guidance and bona fides!
