### ISSUE TITLE
make predictions on MPII testing set

### ISSUE THREAD

**Issue by tangweibh** [bearpaw/PyraNet#2]
Hi,

Thanks so much for your sharing the codes. 

How can I use a trained model to make predictions on the MPII testing set and generate the .MAT file that can be evaluated by the mpii website http://human-pose.mpi-inf.mpg.de? Have you implemented such functions in your codes?

**Comment by bearpaw** [comment]
Hi, you could apply our models to the testing images and save the results the same format as the annotations of the MPII dataset. Please follow their instructions to prepare the final results: http://human-pose.mpi-inf.mpg.de/#evaluation

**Comment by MissYOLY** [comment]
@tangweibh ,@bearpaw
I have the same problem, how to make a prediction for mpii, I used the result pred_post_ .h5 to generate predictions, but was told that it was wrong.

**Comment by 738654805** [comment]
@MissYOLY You can visit this page https://github.com/anibali/eval-mpii-pose.

**Comment by MissYOLY** [comment]
@738654805 Thank you for your help. I will try.
