### ISSUE TITLE
Can you share the code about LSP dataset of Pyranet(lua)?

### ISSUE THREAD

**Issue by Posecc-wcl** [bearpaw/PyraNet#21]
I have a SCI overhaul needs the result of PCK@0.2. Thank you very much

**Comment by bearpaw** [comment]
Person-centric PCK@0.2 on LSP dataset is reported in Table 2 of our paper, see https://arxiv.org/pdf/1708.01101.pdf
You can also download all the predictions from here: http://human-pose.mpi-inf.mpg.de/#related_benchmarks
