### ISSUE TITLE
where is the parameter initialization code described in your paper?

### ISSUE THREAD

**Issue by xmyqsh** [bearpaw/PyraNet#3]
Hi,
I haven't found the parameter initialization described in your paper in this implementation.

**Comment by bearpaw** [comment]
@xmyqsh  Thanks for your interest in our paper. The initialization part is not included in this code. We plan to include it in the pytorch version in the recent future. Please stay tuned!

**Comment by xmyqsh** [comment]
@bearpaw 
Sounds good! Wonderful work!
