### ISSUE TITLE
Your Final model

### ISSUE THREAD

**Issue by liruilong940607** [bearpaw/PyraNet#4]
Thank you for sharing your wonderful work!

Is the model in Google Drive the same one you used to get 1st on MPII ? If that's so, that means you finally choose a 8-stack structure? 

Have you done some experiments about number of stack based on your RPM ? For example, is there a big gap on performance between 2-stack and 8-stack?

Looking forward to your response!

**Comment by bearpaw** [comment]
Yes, it's an 8-stack model.

Results of 2-stack model on the MPII validation set can be found in the paper (Figure. 8). The gap is about 1 to 2 PCKh score.
