### ISSUE TITLE
How can get my hdf5 annotation data?

### ISSUE THREAD

**Issue by tyduck** [bearpaw/PyraNet#5]
I want to train the model from a different dataset, then I find a problem, how can I get the hdf5 annotation data by myself? Could the author publish the code about how to transform the label data  in the original dataset to the hdf5 formation?

**Comment by bearpaw** [comment]
Hi, the h5 files are directly borrowed from https://github.com/umich-vl/pose-hg-train/tree/master/data/mpii/annot 
We don't have code for generating data in h5 format.
However, we have code for converting the annotation of MPII to JSON format. You may refer to our [pytorch-pose](https://github.com/bearpaw/pytorch-pose) repository.
